on:
  push:
    branches:
      - master
      - develop
      - verif
      - invert
      - ctrl-combos
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
    branches:
      - master
      - develop

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
